//
//  BasicWords.swift
//  KeyboardLingo
//
//  Created by Anton on 2024-12-25.
//

let basicWords: [Word] = [
    Word(jp: "私", jpExtra: "わたし", en: "I, me"),
    Word(jp: "あなた", jpExtra: nil, en: "You"),
    Word(jp: "彼", jpExtra: "かれ", en: "He, him"),
    Word(jp: "彼女", jpExtra: "かのじょ", en: "She, her"),
    Word(jp: "これ", jpExtra: nil, en: "This"),
    Word(jp: "それ", jpExtra: nil, en: "That"),
    Word(jp: "あれ", jpExtra: nil, en: "That (over there)"),
    Word(jp: "ここ", jpExtra: nil, en: "Here"),
    Word(jp: "そこ", jpExtra: nil, en: "There"),
    Word(jp: "はい", jpExtra: nil, en: "Yes"),
    Word(jp: "いいえ", jpExtra: nil, en: "No"),
    Word(jp: "ありがとう", jpExtra: nil, en: "Thank you"),
    Word(jp: "すみません", jpExtra: nil, en: "Excuse me"),
    Word(jp: "ごめんなさい", jpExtra: nil, en: "Sorry"),
    Word(jp: "おはようございます", jpExtra: nil, en: "Good morning"),
    Word(jp: "こんにちは", jpExtra: nil, en: "Hello"),
    Word(jp: "こんばんは", jpExtra: nil, en: "Good evening"),
    Word(jp: "さようなら", jpExtra: nil, en: "Goodbye"),
    Word(jp: "何", jpExtra: "なに", en: "What"),
    Word(jp: "どこ", jpExtra: nil, en: "Where"),
    Word(jp: "誰", jpExtra: "だれ", en: "Who"),
    Word(jp: "なぜ", jpExtra: nil, en: "Why"),
    Word(jp: "どうして", jpExtra: nil, en: "Why (formal)"),
    Word(jp: "どうやって", jpExtra: nil, en: "How"),
    Word(jp: "いくら", jpExtra: nil, en: "How much"),
    Word(jp: "人", jpExtra: "ひと", en: "Person"),
    Word(jp: "子供", jpExtra: "こども", en: "Child"),
    Word(jp: "大人", jpExtra: "おとな", en: "Adult"),
    Word(jp: "男性", jpExtra: "だんせい", en: "Man"),
    Word(jp: "女性", jpExtra: "じょせい", en: "Woman"),
    Word(jp: "食べる", jpExtra: "たべる", en: "To eat"),
    Word(jp: "飲む", jpExtra: "のむ", en: "To drink"),
    Word(jp: "行く", jpExtra: "いく", en: "To go"),
    Word(jp: "来る", jpExtra: "くる", en: "To come"),
    Word(jp: "見る", jpExtra: "みる", en: "To see"),
    Word(jp: "聞く", jpExtra: "きく", en: "To listen"),
    Word(jp: "話す", jpExtra: "はなす", en: "To speak"),
    Word(jp: "書く", jpExtra: "かく", en: "To write"),
    Word(jp: "読む", jpExtra: "よむ", en: "To read"),
    Word(jp: "買う", jpExtra: "かう", en: "To buy"),
    Word(jp: "新しい", jpExtra: "あたらしい", en: "New"),
    Word(jp: "古い", jpExtra: "ふるい", en: "Old"),
    Word(jp: "大きい", jpExtra: "おおきい", en: "Big"),
    Word(jp: "小さい", jpExtra: "ちいさい", en: "Small"),
    Word(jp: "高い", jpExtra: "たかい", en: "Expensive, high"),
    Word(jp: "安い", jpExtra: "やすい", en: "Cheap"),
    Word(jp: "楽しい", jpExtra: "たのしい", en: "Fun"),
    Word(jp: "忙しい", jpExtra: "いそがしい", en: "Busy"),
    Word(jp: "暇", jpExtra: "ひま", en: "Free time"),
    Word(jp: "時間", jpExtra: "じかん", en: "Time"),
    Word(jp: "お金", jpExtra: "おかね", en: "Money"),
    Word(jp: "月", jpExtra: "つき", en: "Moon, month"),
    Word(jp: "火", jpExtra: "ひ", en: "Fire"),
    Word(jp: "水", jpExtra: "みず", en: "Water"),
    Word(jp: "木", jpExtra: "き", en: "Tree, wood"),
    Word(jp: "金", jpExtra: "きん", en: "Gold"),
    Word(jp: "土", jpExtra: "つち", en: "Earth, soil"),
    Word(jp: "日", jpExtra: "ひ", en: "Sun, day"),
    Word(jp: "春", jpExtra: "はる", en: "Spring"),
    Word(jp: "夏", jpExtra: "なつ", en: "Summer"),
    Word(jp: "秋", jpExtra: "あき", en: "Autumn"),
    Word(jp: "冬", jpExtra: "ふゆ", en: "Winter"),
    Word(jp: "先生", jpExtra: "せんせい", en: "Teacher"),
    Word(jp: "学生", jpExtra: "がくせい", en: "Student"),
    Word(jp: "病院", jpExtra: "びょういん", en: "Hospital"),
    Word(jp: "家", jpExtra: "いえ", en: "House"),
    Word(jp: "部屋", jpExtra: "へや", en: "Room"),
    Word(jp: "店", jpExtra: "みせ", en: "Shop"),
    Word(jp: "車", jpExtra: "くるま", en: "Car"),
    Word(jp: "電車", jpExtra: "でんしゃ", en: "Train"),
    Word(jp: "駅", jpExtra: "えき", en: "Station"),
    Word(jp: "空港", jpExtra: "くうこう", en: "Airport"),
    Word(jp: "飛行機", jpExtra: "ひこうき", en: "Airplane"),
    Word(jp: "海", jpExtra: "うみ", en: "Sea"),
    Word(jp: "山", jpExtra: "やま", en: "Mountain"),
    Word(jp: "雨", jpExtra: "あめ", en: "Rain"),
    Word(jp: "雪", jpExtra: "ゆき", en: "Snow"),
    Word(jp: "天気", jpExtra: "てんき", en: "Weather"),
    Word(jp: "道", jpExtra: "みち", en: "Road"),
    Word(jp: "右", jpExtra: "みぎ", en: "Right"),
    Word(jp: "左", jpExtra: "ひだり", en: "Left"),
    Word(jp: "前", jpExtra: "まえ", en: "Front"),
    Word(jp: "後ろ", jpExtra: "うしろ", en: "Behind"),
    Word(jp: "上", jpExtra: "うえ", en: "Up"),
    Word(jp: "下", jpExtra: "した", en: "Down"),
]
