//
//  CafeWords.swift
//  KeyboardLingo
//
//  Created by Anton on 2024-12-25.
//

let cafeWords: [Word] = [
    Word(jp: "メニュー", jpExtra: nil, en: "Menu"),
    Word(jp: "注文", jpExtra: "ちゅうもん", en: "Order"),
    Word(jp: "予約", jpExtra: "よやく", en: "Reservation"),
    Word(jp: "席", jpExtra: "せき", en: "Seat"),
    Word(jp: "禁煙席", jpExtra: "きんえんせき", en: "Non-Smoking Seat"),
    Word(jp: "喫煙席", jpExtra: "きつえんせき", en: "Smoking Seat"),
    Word(jp: "店員", jpExtra: "てんいん", en: "Waiter/Waitress"),
    Word(jp: "お客さん", jpExtra: "おきゃくさん", en: "Customer"),
    Word(jp: "レジ", jpExtra: nil, en: "Cash Register"),
    Word(jp: "支払い", jpExtra: "しはらい", en: "Payment"),
    Word(jp: "現金", jpExtra: "げんきん", en: "Cash"),
    Word(jp: "クレジットカード", jpExtra: nil, en: "Credit Card"),
    Word(jp: "領収書", jpExtra: "りょうしゅうしょ", en: "Receipt"),
    Word(jp: "伝票", jpExtra: "でんぴょう", en: "Bill"),
    Word(jp: "おすすめ", jpExtra: nil, en: "Recommendation"),
    Word(jp: "注文を取る", jpExtra: "ちゅうもんをとる", en: "Take Order"),
    Word(jp: "料理", jpExtra: "りょうり", en: "Dish"),
    Word(jp: "飲み物", jpExtra: "のみもの", en: "Drink"),
    Word(jp: "前菜", jpExtra: "ぜんさい", en: "Appetizer"),
    Word(jp: "主菜", jpExtra: "しゅさい", en: "Main Dish"),
    Word(jp: "デザート", jpExtra: nil, en: "Dessert"),
    Word(jp: "スープ", jpExtra: nil, en: "Soup"),
    Word(jp: "サラダ", jpExtra: nil, en: "Salad"),
    Word(jp: "セットメニュー", jpExtra: nil, en: "Set Menu"),
    Word(jp: "単品", jpExtra: "たんぴん", en: "A La Carte"),
    Word(jp: "ドリンクバー", jpExtra: nil, en: "Drink Bar"),
    Word(jp: "おかわり", jpExtra: nil, en: "Refill"),
    Word(jp: "テイクアウト", jpExtra: nil, en: "Takeout"),
    Word(jp: "持ち帰り", jpExtra: "もちかえり", en: "Takeout (Formal)"),
    Word(jp: "店内", jpExtra: "てんない", en: "Eat-In"),
    Word(jp: "会計", jpExtra: "かいけい", en: "Checkout"),
    Word(jp: "注文票", jpExtra: "ちゅうもんひょう", en: "Order Slip"),
    Word(jp: "ランチメニュー", jpExtra: nil, en: "Lunch Menu"),
    Word(jp: "ディナーメニュー", jpExtra: nil, en: "Dinner Menu"),
    Word(jp: "飲み放題", jpExtra: "のみほうだい", en: "All-You-Can-Drink"),
    Word(jp: "食べ放題", jpExtra: "たべほうだい", en: "All-You-Can-Eat"),
    Word(jp: "グラス", jpExtra: nil, en: "Glass"),
    Word(jp: "カップ", jpExtra: nil, en: "Cup"),
    Word(jp: "ナイフ", jpExtra: nil, en: "Knife"),
    Word(jp: "フォーク", jpExtra: nil, en: "Fork"),
    Word(jp: "スプーン", jpExtra: nil, en: "Spoon"),
    Word(jp: "お箸", jpExtra: "おはし", en: "Chopsticks"),
    Word(jp: "皿", jpExtra: "さら", en: "Plate"),
    Word(jp: "おしぼり", jpExtra: nil, en: "Wet Towel"),
    Word(jp: "予約済み", jpExtra: "よやくずみ", en: "Reserved"),
    Word(jp: "空いている席", jpExtra: "あいているせき", en: "Available Seat"),
    Word(jp: "満席", jpExtra: "まんせき", en: "Full (No Seats Available)"),
    Word(jp: "一名", jpExtra: "いちめい", en: "One Person"),
    Word(jp: "二名", jpExtra: "にめい", en: "Two People"),
    Word(jp: "注文内容", jpExtra: "ちゅうもんないよう", en: "Order Details"),
    Word(jp: "お会計お願いします", jpExtra: "おかいけいおねがいします", en: "Check, Please"),
    Word(jp: "いらっしゃいませ", jpExtra: nil, en: "Welcome"),
    Word(jp: "ごゆっくりどうぞ", jpExtra: "ごゆっくりどうぞ", en: "Please Enjoy Your Time"),
    Word(jp: "お飲み物はどうしますか", jpExtra: "おのみものはどうしますか", en: "What Would You Like to Drink?"),
    Word(jp: "アレルギー", jpExtra: nil, en: "Allergy"),
    Word(jp: "ベジタリアン", jpExtra: nil, en: "Vegetarian"),
    Word(jp: "ヴィーガン", jpExtra: nil, en: "Vegan"),
    Word(jp: "辛い", jpExtra: "からい", en: "Spicy"),
    Word(jp: "甘い", jpExtra: "あまい", en: "Sweet"),
    Word(jp: "温かい", jpExtra: "あたたかい", en: "Hot"),
    Word(jp: "冷たい", jpExtra: "つめたい", en: "Cold"),
    Word(jp: "薄い", jpExtra: "うすい", en: "Light (Flavor)"),
    Word(jp: "濃い", jpExtra: "こい", en: "Strong (Flavor)"),
    Word(jp: "おかわり自由", jpExtra: "おかわりじゆう", en: "Free Refills"),
    Word(jp: "辛さ調整", jpExtra: "からさちょうせい", en: "Adjust Spice Level")
]
