//
//  FoodWords.swift
//  KeyboardLingo
//
//  Created by Anton on 2024-12-25.
//

let foodWords: [Word] = [
    Word(jp: "ご飯", jpExtra: "ごはん", en: "Rice"),
    Word(jp: "パン", jpExtra: nil, en: "Bread"),
    Word(jp: "麺", jpExtra: "めん", en: "Noodles"),
    Word(jp: "寿司", jpExtra: "すし", en: "Sushi"),
    Word(jp: "刺身", jpExtra: "さしみ", en: "Sashimi"),
    Word(jp: "天ぷら", jpExtra: "てんぷら", en: "Tempura"),
    Word(jp: "お好み焼き", jpExtra: "おこのみやき", en: "Okonomiyaki"),
    Word(jp: "たこ焼き", jpExtra: "たこやき", en: "Takoyaki"),
    Word(jp: "焼肉", jpExtra: "やきにく", en: "Grilled Meat"),
    Word(jp: "しゃぶしゃぶ", jpExtra: nil, en: "Shabu-shabu"),
    Word(jp: "ラーメン", jpExtra: nil, en: "Ramen"),
    Word(jp: "そば", jpExtra: nil, en: "Soba"),
    Word(jp: "うどん", jpExtra: nil, en: "Udon"),
    Word(jp: "カレー", jpExtra: nil, en: "Curry"),
    Word(jp: "卵", jpExtra: "たまご", en: "Egg"),
    Word(jp: "豆腐", jpExtra: "とうふ", en: "Tofu"),
    Word(jp: "野菜", jpExtra: "やさい", en: "Vegetables"),
    Word(jp: "果物", jpExtra: "くだもの", en: "Fruits"),
    Word(jp: "りんご", jpExtra: nil, en: "Apple"),
    Word(jp: "みかん", jpExtra: nil, en: "Mandarin Orange"),
    Word(jp: "バナナ", jpExtra: nil, en: "Banana"),
    Word(jp: "いちご", jpExtra: nil, en: "Strawberry"),
    Word(jp: "さくらんぼ", jpExtra: nil, en: "Cherry"),
    Word(jp: "スイカ", jpExtra: nil, en: "Watermelon"),
    Word(jp: "レモン", jpExtra: nil, en: "Lemon"),
    Word(jp: "ピーチ", jpExtra: nil, en: "Peach"),
    Word(jp: "きゅうり", jpExtra: nil, en: "Cucumber"),
    Word(jp: "トマト", jpExtra: nil, en: "Tomato"),
    Word(jp: "キャベツ", jpExtra: nil, en: "Cabbage"),
    Word(jp: "玉ねぎ", jpExtra: "たまねぎ", en: "Onion"),
    Word(jp: "にんじん", jpExtra: nil, en: "Carrot"),
    Word(jp: "じゃがいも", jpExtra: nil, en: "Potato"),
    Word(jp: "ほうれん草", jpExtra: "ほうれんそう", en: "Spinach"),
    Word(jp: "ピーマン", jpExtra: nil, en: "Bell Pepper"),
    Word(jp: "ナス", jpExtra: nil, en: "Eggplant"),
    Word(jp: "かぼちゃ", jpExtra: nil, en: "Pumpkin"),
    Word(jp: "魚", jpExtra: "さかな", en: "Fish"),
    Word(jp: "肉", jpExtra: "にく", en: "Meat"),
    Word(jp: "鶏肉", jpExtra: "とりにく", en: "Chicken"),
    Word(jp: "豚肉", jpExtra: "ぶたにく", en: "Pork"),
    Word(jp: "牛肉", jpExtra: "ぎゅうにく", en: "Beef"),
    Word(jp: "羊肉", jpExtra: "ようにく", en: "Lamb"),
    Word(jp: "ソーセージ", jpExtra: nil, en: "Sausage"),
    Word(jp: "ベーコン", jpExtra: nil, en: "Bacon"),
    Word(jp: "ハム", jpExtra: nil, en: "Ham"),
    Word(jp: "チーズ", jpExtra: nil, en: "Cheese"),
    Word(jp: "バター", jpExtra: nil, en: "Butter"),
    Word(jp: "ヨーグルト", jpExtra: nil, en: "Yogurt"),
    Word(jp: "牛乳", jpExtra: "ぎゅうにゅう", en: "Milk"),
    Word(jp: "コーヒー", jpExtra: nil, en: "Coffee"),
    Word(jp: "紅茶", jpExtra: "こうちゃ", en: "Tea"),
    Word(jp: "お茶", jpExtra: "おちゃ", en: "Green Tea"),
    Word(jp: "ジュース", jpExtra: nil, en: "Juice"),
    Word(jp: "ビール", jpExtra: nil, en: "Beer"),
    Word(jp: "ワイン", jpExtra: nil, en: "Wine"),
    Word(jp: "ウイスキー", jpExtra: nil, en: "Whiskey"),
    Word(jp: "日本酒", jpExtra: "にほんしゅ", en: "Sake"),
    Word(jp: "焼酎", jpExtra: "しょうちゅう", en: "Shochu"),
    Word(jp: "炭酸飲料", jpExtra: "たんさんいんりょう", en: "Soda"),
    Word(jp: "水", jpExtra: "みず", en: "Water"),
    Word(jp: "ミネラルウォーター", jpExtra: nil, en: "Mineral Water"),
    Word(jp: "アイスクリーム", jpExtra: nil, en: "Ice Cream"),
    Word(jp: "ケーキ", jpExtra: nil, en: "Cake"),
    Word(jp: "クッキー", jpExtra: nil, en: "Cookie"),
    Word(jp: "チョコレート", jpExtra: nil, en: "Chocolate"),
    Word(jp: "飴", jpExtra: "あめ", en: "Candy"),
    Word(jp: "せんべい", jpExtra: nil, en: "Rice Cracker"),
    Word(jp: "餅", jpExtra: "もち", en: "Rice Cake"),
    Word(jp: "スナック菓子", jpExtra: "スナックがし", en: "Snacks"),
    Word(jp: "ポテトチップス", jpExtra: nil, en: "Potato Chips"),
    Word(jp: "ピザ", jpExtra: nil, en: "Pizza"),
    Word(jp: "サンドイッチ", jpExtra: nil, en: "Sandwich"),
    Word(jp: "ハンバーガー", jpExtra: nil, en: "Hamburger"),
    Word(jp: "フライドポテト", jpExtra: nil, en: "French Fries"),
    Word(jp: "サラダ", jpExtra: nil, en: "Salad"),
    Word(jp: "スープ", jpExtra: nil, en: "Soup"),
    Word(jp: "デザート", jpExtra: nil, en: "Dessert"),
    Word(jp: "醤油", jpExtra: "しょうゆ", en: "Soy Sauce"),
    Word(jp: "味噌", jpExtra: "みそ", en: "Miso"),
    Word(jp: "塩", jpExtra: "しお", en: "Salt"),
    Word(jp: "砂糖", jpExtra: "さとう", en: "Sugar"),
    Word(jp: "酢", jpExtra: "す", en: "Vinegar"),
    Word(jp: "油", jpExtra: "あぶら", en: "Oil")
]
