//
//  HouseWords.swift
//  KeyboardLingo
//
//  Created by Anton on 2024-12-25.
//

let houseWords: [Word] = [
    Word(jp: "家具", jpExtra: "かぐ", en: "Furniture"),
    Word(jp: "椅子", jpExtra: "いす", en: "Chair"),
    Word(jp: "テーブル", jpExtra: nil, en: "Table"),
    Word(jp: "ベッド", jpExtra: nil, en: "Bed"),
    Word(jp: "ソファ", jpExtra: nil, en: "Sofa"),
    Word(jp: "クローゼット", jpExtra: nil, en: "Closet"),
    Word(jp: "本棚", jpExtra: "ほんだな", en: "Bookshelf"),
    Word(jp: "鏡", jpExtra: "かがみ", en: "Mirror"),
    Word(jp: "カーペット", jpExtra: nil, en: "Carpet"),
    Word(jp: "ラグ", jpExtra: nil, en: "Rug"),
    Word(jp: "ランプ", jpExtra: nil, en: "Lamp"),
    Word(jp: "電球", jpExtra: "でんきゅう", en: "Light Bulb"),
    Word(jp: "窓", jpExtra: "まど", en: "Window"),
    Word(jp: "カーテン", jpExtra: nil, en: "Curtain"),
    Word(jp: "ドア", jpExtra: nil, en: "Door"),
    Word(jp: "玄関", jpExtra: "げんかん", en: "Entrance"),
    Word(jp: "台所", jpExtra: "だいどころ", en: "Kitchen"),
    Word(jp: "冷蔵庫", jpExtra: "れいぞうこ", en: "Refrigerator"),
    Word(jp: "電子レンジ", jpExtra: "でんしレンジ", en: "Microwave"),
    Word(jp: "トースター", jpExtra: nil, en: "Toaster"),
    Word(jp: "炊飯器", jpExtra: "すいはんき", en: "Rice Cooker"),
    Word(jp: "フライパン", jpExtra: nil, en: "Frying Pan"),
    Word(jp: "鍋", jpExtra: "なべ", en: "Pot"),
    Word(jp: "包丁", jpExtra: "ほうちょう", en: "Kitchen Knife"),
    Word(jp: "まな板", jpExtra: "まないた", en: "Cutting Board"),
    Word(jp: "皿", jpExtra: "さら", en: "Plate"),
    Word(jp: "お椀", jpExtra: "おわん", en: "Bowl"),
    Word(jp: "箸", jpExtra: "はし", en: "Chopsticks"),
    Word(jp: "フォーク", jpExtra: nil, en: "Fork"),
    Word(jp: "スプーン", jpExtra: nil, en: "Spoon"),
    Word(jp: "コップ", jpExtra: nil, en: "Glass"),
    Word(jp: "マグカップ", jpExtra: nil, en: "Mug"),
    Word(jp: "湯飲み", jpExtra: "ゆのみ", en: "Teacup"),
    Word(jp: "急須", jpExtra: "きゅうす", en: "Teapot"),
    Word(jp: "洗濯機", jpExtra: "せんたくき", en: "Washing Machine"),
    Word(jp: "掃除機", jpExtra: "そうじき", en: "Vacuum Cleaner"),
    Word(jp: "アイロン", jpExtra: nil, en: "Iron"),
    Word(jp: "洗剤", jpExtra: "せんざい", en: "Detergent"),
    Word(jp: "ほうき", jpExtra: nil, en: "Broom"),
    Word(jp: "ちりとり", jpExtra: nil, en: "Dustpan"),
    Word(jp: "ゴミ箱", jpExtra: "ごみばこ", en: "Trash Can"),
    Word(jp: "タオル", jpExtra: nil, en: "Towel"),
    Word(jp: "バスタオル", jpExtra: nil, en: "Bath Towel"),
    Word(jp: "シャンプー", jpExtra: nil, en: "Shampoo"),
    Word(jp: "リンス", jpExtra: nil, en: "Conditioner"),
    Word(jp: "せっけん", jpExtra: nil, en: "Soap"),
    Word(jp: "歯ブラシ", jpExtra: "はブラシ", en: "Toothbrush"),
    Word(jp: "歯磨き粉", jpExtra: "はみがきこ", en: "Toothpaste"),
    Word(jp: "お風呂", jpExtra: "おふろ", en: "Bathtub"),
    Word(jp: "シャワー", jpExtra: nil, en: "Shower"),
    Word(jp: "トイレ", jpExtra: nil, en: "Toilet"),
    Word(jp: "便座", jpExtra: "べんざ", en: "Toilet Seat"),
    Word(jp: "トイレットペーパー", jpExtra: nil, en: "Toilet Paper"),
    Word(jp: "タンス", jpExtra: nil, en: "Chest of Drawers"),
    Word(jp: "布団", jpExtra: "ふとん", en: "Futon"),
    Word(jp: "毛布", jpExtra: "もうふ", en: "Blanket"),
    Word(jp: "枕", jpExtra: "まくら", en: "Pillow"),
    Word(jp: "シーツ", jpExtra: nil, en: "Sheet"),
    Word(jp: "掛け布団", jpExtra: "かけぶとん", en: "Duvet"),
    Word(jp: "カレンダー", jpExtra: nil, en: "Calendar"),
    Word(jp: "時計", jpExtra: "とけい", en: "Clock"),
    Word(jp: "扇風機", jpExtra: "せんぷうき", en: "Fan"),
    Word(jp: "エアコン", jpExtra: nil, en: "Air Conditioner"),
    Word(jp: "暖房", jpExtra: "だんぼう", en: "Heater"),
    Word(jp: "加湿器", jpExtra: "かしつき", en: "Humidifier"),
    Word(jp: "空気清浄機", jpExtra: "くうきせいじょうき", en: "Air Purifier"),
    Word(jp: "電池", jpExtra: "でんち", en: "Battery"),
    Word(jp: "延長コード", jpExtra: "えんちょうコード", en: "Extension Cord"),
    Word(jp: "充電器", jpExtra: "じゅうでんき", en: "Charger"),
    Word(jp: "スイッチ", jpExtra: nil, en: "Switch"),
    Word(jp: "リモコン", jpExtra: nil, en: "Remote Control"),
    Word(jp: "インターホン", jpExtra: nil, en: "Intercom"),
    Word(jp: "郵便受け", jpExtra: "ゆうびんうけ", en: "Mailbox"),
    Word(jp: "玄関マット", jpExtra: "げんかんマット", en: "Doormat"),
    Word(jp: "花瓶", jpExtra: "かびん", en: "Vase"),
    Word(jp: "観葉植物", jpExtra: "かんようしょくぶつ", en: "House Plant"),
    Word(jp: "絵画", jpExtra: "かいが", en: "Painting"),
    Word(jp: "写真立て", jpExtra: "しゃしんたて", en: "Photo Frame"),
    Word(jp: "傘立て", jpExtra: "かさたて", en: "Umbrella Stand"),
    Word(jp: "温度計", jpExtra: "おんどけい", en: "Thermometer"),
    Word(jp: "スリッパ", jpExtra: nil, en: "Slippers")
]
