//
//  TechWords.swift
//  KeyboardLingo
//
//  Created by Anton on 2024-12-25.
//

let techWords: [Word] = [
    Word(jp: "プログラミング", jpExtra: nil, en: "Programming"),
    Word(jp: "コード", jpExtra: nil, en: "Code"),
    Word(jp: "デバッグ", jpExtra: nil, en: "Debugging"),
    Word(jp: "コンパイル", jpExtra: nil, en: "Compile"),
    Word(jp: "アルゴリズム", jpExtra: nil, en: "Algorithm"),
    Word(jp: "データベース", jpExtra: nil, en: "Database"),
    Word(jp: "サーバー", jpExtra: nil, en: "Server"),
    Word(jp: "クライアント", jpExtra: nil, en: "Client"),
    Word(jp: "ネットワーク", jpExtra: nil, en: "Network"),
    Word(jp: "人工知能", jpExtra: "じんこうちのう", en: "Artificial Intelligence"),
    Word(jp: "機械学習", jpExtra: "きかいがくしゅう", en: "Machine Learning"),
    Word(jp: "深層学習", jpExtra: "しんそうがくしゅう", en: "Deep Learning"),
    Word(jp: "大規模データ", jpExtra: "だいきぼデータ", en: "Big Data"),
    Word(jp: "設計", jpExtra: "せっけい", en: "Design"),
    Word(jp: "構造", jpExtra: "こうぞう", en: "Structure"),
    Word(jp: "ライブラリ", jpExtra: nil, en: "Library"),
    Word(jp: "モジュール", jpExtra: nil, en: "Module"),
    Word(jp: "スクリプト", jpExtra: nil, en: "Script"),
    Word(jp: "フォルダ", jpExtra: nil, en: "Folder"),
    Word(jp: "更新", jpExtra: "こうしん", en: "Update"),
    Word(jp: "技術", jpExtra: "ぎじゅつ", en: "Technology"),
    Word(jp: "暗号化", jpExtra: "あんごうか", en: "Encryption"),
    Word(jp: "設置", jpExtra: "せっち", en: "Installation"),
    Word(jp: "統合", jpExtra: "とうごう", en: "Integration"),
    Word(jp: "分散", jpExtra: "ぶんさん", en: "Distribution"),
    Word(jp: "演算", jpExtra: "えんざん", en: "Computation"),
    Word(jp: "仮想化", jpExtra: "かそうか", en: "Virtualization"),
    Word(jp: "運用", jpExtra: "うんよう", en: "Operation"),
    Word(jp: "保守", jpExtra: "ほしゅ", en: "Maintenance"),
    Word(jp: "管理", jpExtra: "かんり", en: "Management"),
    Word(jp: "性能", jpExtra: "せいのう", en: "Performance"),
    Word(jp: "検証", jpExtra: "けんしょう", en: "Verification"),
    Word(jp: "開発", jpExtra: "かいはつ", en: "Development"),
    Word(jp: "計測", jpExtra: "けいそく", en: "Measurement"),
    Word(jp: "構築", jpExtra: "こうちく", en: "Construction"),
    Word(jp: "解析", jpExtra: "かいせき", en: "Analysis"),
    Word(jp: "最適化", jpExtra: "さいてきか", en: "Optimization"),
    Word(jp: "電源", jpExtra: "でんげん", en: "Power Supply"),
    Word(jp: "信号", jpExtra: "しんごう", en: "Signal"),
    Word(jp: "電子", jpExtra: "でんし", en: "Electronics"),
    Word(jp: "通信", jpExtra: "つうしん", en: "Communication"),
    Word(jp: "記録", jpExtra: "きろく", en: "Recording"),
    Word(jp: "再生", jpExtra: "さいせい", en: "Playback"),
    Word(jp: "検索", jpExtra: "けんさく", en: "Search"),
    Word(jp: "保存", jpExtra: "ほぞん", en: "Storage"),
    Word(jp: "表示", jpExtra: "ひょうじ", en: "Display"),
    Word(jp: "編集", jpExtra: "へんしゅう", en: "Editing"),
    Word(jp: "圧縮", jpExtra: "あっしゅく", en: "Compression"),
    Word(jp: "解凍", jpExtra: "かいとう", en: "Decompression"),
    Word(jp: "仮想空間", jpExtra: "かそうくうかん", en: "Virtual Space"),
    Word(jp: "拡張現実", jpExtra: "かくちょうげんじつ", en: "Augmented Reality"),
    Word(jp: "音声認識", jpExtra: "おんせいにんしき", en: "Speech Recognition"),
    Word(jp: "画像処理", jpExtra: "がぞうしょり", en: "Image Processing"),
    Word(jp: "映像", jpExtra: "えいぞう", en: "Video"),
    Word(jp: "音響", jpExtra: "おんきょう", en: "Acoustics"),
    Word(jp: "配信", jpExtra: "はいしん", en: "Streaming"),
    Word(jp: "電波", jpExtra: "でんぱ", en: "Radio Wave"),
    Word(jp: "光学", jpExtra: "こうがく", en: "Optics"),
    Word(jp: "導入", jpExtra: "どうにゅう", en: "Introduction"),
    Word(jp: "互換性", jpExtra: "ごかんせい", en: "Compatibility"),
    Word(jp: "拡張", jpExtra: "かくちょう", en: "Expansion"),
    Word(jp: "縮小", jpExtra: "しゅくしょう", en: "Reduction"),
    Word(jp: "分割", jpExtra: "ぶんかつ", en: "Segmentation"),
    Word(jp: "組み立て", jpExtra: "くみたて", en: "Assembly"),
    Word(jp: "計算", jpExtra: "けいさん", en: "Calculation"),
    Word(jp: "同期", jpExtra: "どうき", en: "Synchronization"),
    Word(jp: "非同期", jpExtra: "ひどうき", en: "Asynchronous"),
    Word(jp: "認証", jpExtra: "にんしょう", en: "Authentication"),
    Word(jp: "保護", jpExtra: "ほご", en: "Protection"),
    Word(jp: "遮断", jpExtra: "しゃだん", en: "Blocking"),
    Word(jp: "復元", jpExtra: "ふくげん", en: "Restoration"),
    Word(jp: "負荷", jpExtra: "ふか", en: "Load"),
    Word(jp: "分散処理", jpExtra: "ぶんさんしょり", en: "Distributed Processing"),
    Word(jp: "設定", jpExtra: "せってい", en: "Configuration"),
    Word(jp: "処理速度", jpExtra: "しょりそくど", en: "Processing Speed"),
    Word(jp: "応答時間", jpExtra: "おうとうじかん", en: "Response Time"),
    Word(jp: "画面", jpExtra: "がめん", en: "Screen"),
    Word(jp: "圧力", jpExtra: "あつりょく", en: "Pressure"),
    Word(jp: "触覚", jpExtra: "しょっかく", en: "Haptics"),
    Word(jp: "信頼性", jpExtra: "しんらいせい", en: "Reliability"),
    Word(jp: "柔軟性", jpExtra: "じゅうなんせい", en: "Flexibility"),
    Word(jp: "適応", jpExtra: "てきおう", en: "Adaptation")
]
