//
//  TravelWords.swift
//  KeyboardLingo
//
//  Created by Anton on 2024-12-25.
//

let travelWords: [Word] = [
    Word(jp: "旅行", jpExtra: "りょこう", en: "Travel"),
    Word(jp: "観光", jpExtra: "かんこう", en: "Sightseeing"),
    Word(jp: "航空券", jpExtra: "こうくうけん", en: "Plane Ticket"),
    Word(jp: "旅券", jpExtra: "りょけん", en: "Passport"),
    Word(jp: "出発", jpExtra: "しゅっぱつ", en: "Departure"),
    Word(jp: "到着", jpExtra: "とうちゃく", en: "Arrival"),
    Word(jp: "空港", jpExtra: "くうこう", en: "Airport"),
    Word(jp: "駅", jpExtra: "えき", en: "Station"),
    Word(jp: "バス停", jpExtra: "バスてい", en: "Bus Stop"),
    Word(jp: "電車", jpExtra: "でんしゃ", en: "Train"),
    Word(jp: "新幹線", jpExtra: "しんかんせん", en: "Bullet Train"),
    Word(jp: "タクシー", jpExtra: nil, en: "Taxi"),
    Word(jp: "レンタカー", jpExtra: nil, en: "Rental Car"),
    Word(jp: "地図", jpExtra: "ちず", en: "Map"),
    Word(jp: "道", jpExtra: "みち", en: "Road"),
    Word(jp: "案内所", jpExtra: "あんないじょ", en: "Information Desk"),
    Word(jp: "宿泊", jpExtra: "しゅくはく", en: "Accommodation"),
    Word(jp: "ホテル", jpExtra: nil, en: "Hotel"),
    Word(jp: "旅館", jpExtra: "りょかん", en: "Traditional Inn"),
    Word(jp: "ホステル", jpExtra: nil, en: "Hostel"),
    Word(jp: "キャンプ場", jpExtra: "キャンプじょう", en: "Campground"),
    Word(jp: "予約", jpExtra: "よやく", en: "Reservation"),
    Word(jp: "部屋", jpExtra: "へや", en: "Room"),
    Word(jp: "荷物", jpExtra: "にもつ", en: "Luggage"),
    Word(jp: "スーツケース", jpExtra: nil, en: "Suitcase"),
    Word(jp: "バックパック", jpExtra: nil, en: "Backpack"),
    Word(jp: "ガイドブック", jpExtra: nil, en: "Guidebook"),
    Word(jp: "観光地", jpExtra: "かんこうち", en: "Tourist Spot"),
    Word(jp: "名所", jpExtra: "めいしょ", en: "Famous Place"),
    Word(jp: "温泉", jpExtra: "おんせん", en: "Hot Spring"),
    Word(jp: "山", jpExtra: "やま", en: "Mountain"),
    Word(jp: "海", jpExtra: "うみ", en: "Sea"),
    Word(jp: "ビーチ", jpExtra: nil, en: "Beach"),
    Word(jp: "島", jpExtra: "しま", en: "Island"),
    Word(jp: "川", jpExtra: "かわ", en: "River"),
    Word(jp: "公園", jpExtra: "こうえん", en: "Park"),
    Word(jp: "美術館", jpExtra: "びじゅつかん", en: "Art Museum"),
    Word(jp: "博物館", jpExtra: "はくぶつかん", en: "Museum"),
    Word(jp: "お土産", jpExtra: "おみやげ", en: "Souvenir"),
    Word(jp: "写真", jpExtra: "しゃしん", en: "Photo"),
    Word(jp: "カメラ", jpExtra: nil, en: "Camera"),
    Word(jp: "切符", jpExtra: "きっぷ", en: "Ticket"),
    Word(jp: "現金", jpExtra: "げんきん", en: "Cash"),
    Word(jp: "クレジットカード", jpExtra: nil, en: "Credit Card"),
    Word(jp: "通貨", jpExtra: "つうか", en: "Currency"),
    Word(jp: "両替", jpExtra: "りょうがえ", en: "Currency Exchange"),
    Word(jp: "レストラン", jpExtra: nil, en: "Restaurant"),
    Word(jp: "カフェ", jpExtra: nil, en: "Cafe"),
    Word(jp: "メニュー", jpExtra: nil, en: "Menu"),
    Word(jp: "料理", jpExtra: "りょうり", en: "Cuisine"),
    Word(jp: "飲み物", jpExtra: "のみもの", en: "Drink"),
    Word(jp: "お酒", jpExtra: "おさけ", en: "Alcohol"),
    Word(jp: "水", jpExtra: "みず", en: "Water"),
    Word(jp: "観光バス", jpExtra: "かんこうバス", en: "Tour Bus"),
    Word(jp: "英語", jpExtra: "えいご", en: "English"),
    Word(jp: "日本語", jpExtra: "にほんご", en: "Japanese"),
    Word(jp: "通訳", jpExtra: "つうやく", en: "Interpreter"),
    Word(jp: "免税店", jpExtra: "めんぜいてん", en: "Duty-Free Shop"),
    Word(jp: "チェックイン", jpExtra: nil, en: "Check-in"),
    Word(jp: "チェックアウト", jpExtra: nil, en: "Check-out"),
    Word(jp: "観光客", jpExtra: "かんこうきゃく", en: "Tourist"),
    Word(jp: "現地", jpExtra: "げんち", en: "Local"),
    Word(jp: "交通", jpExtra: "こうつう", en: "Transportation"),
    Word(jp: "時刻表", jpExtra: "じこくひょう", en: "Timetable"),
    Word(jp: "天気予報", jpExtra: "てんきよほう", en: "Weather Forecast"),
    Word(jp: "事故", jpExtra: "じこ", en: "Accident"),
    Word(jp: "安全", jpExtra: "あんぜん", en: "Safety"),
    Word(jp: "緊急", jpExtra: "きんきゅう", en: "Emergency"),
    Word(jp: "警察", jpExtra: "けいさつ", en: "Police"),
    Word(jp: "病院", jpExtra: "びょういん", en: "Hospital"),
    Word(jp: "薬", jpExtra: "くすり", en: "Medicine"),
    Word(jp: "保険", jpExtra: "ほけん", en: "Insurance"),
    Word(jp: "電話", jpExtra: "でんわ", en: "Phone"),
    Word(jp: "充電", jpExtra: "じゅうでん", en: "Charging"),
    Word(jp: "Wi-Fi", jpExtra: nil, en: "Wi-Fi"),
    Word(jp: "信号", jpExtra: "しんごう", en: "Signal"),
    Word(jp: "目的地", jpExtra: "もくてきち", en: "Destination"),
    Word(jp: "冒険", jpExtra: "ぼうけん", en: "Adventure"),
    Word(jp: "体験", jpExtra: "たいけん", en: "Experience"),
    Word(jp: "休暇", jpExtra: "きゅうか", en: "Vacation"),
    Word(jp: "予定", jpExtra: "よてい", en: "Schedule"),
    Word(jp: "出張", jpExtra: "しゅっちょう", en: "Business Trip")
]
