//
//  WeatherWords.swift
//  KeyboardLingo
//
//  Created by a-heestand on 2024/12/25.
//

let weatherWords: [Word] = [
    Word(jp: "天気", jpExtra: "てんき", en: "Weather"),
    Word(jp: "晴れ", jpExtra: "はれ", en: "Sunny"),
    Word(jp: "曇り", jpExtra: "くもり", en: "Cloudy"),
    Word(jp: "雨", jpExtra: "あめ", en: "Rain"),
    Word(jp: "雪", jpExtra: "ゆき", en: "Snow"),
    Word(jp: "雷", jpExtra: "かみなり", en: "Thunder"),
    Word(jp: "嵐", jpExtra: "あらし", en: "Storm"),
    Word(jp: "風", jpExtra: "かぜ", en: "Wind"),
    Word(jp: "強風", jpExtra: "きょうふう", en: "Strong Wind"),
    Word(jp: "台風", jpExtra: "たいふう", en: "Typhoon"),
    Word(jp: "霧", jpExtra: "きり", en: "Fog"),
    Word(jp: "霜", jpExtra: "しも", en: "Frost"),
    Word(jp: "雹", jpExtra: "ひょう", en: "Hail"),
    Word(jp: "湿気", jpExtra: "しっけ", en: "Humidity"),
    Word(jp: "乾燥", jpExtra: "かんそう", en: "Dryness"),
    Word(jp: "気温", jpExtra: "きおん", en: "Temperature"),
    Word(jp: "暑い", jpExtra: "あつい", en: "Hot"),
    Word(jp: "寒い", jpExtra: "さむい", en: "Cold"),
    Word(jp: "涼しい", jpExtra: "すずしい", en: "Cool"),
    Word(jp: "暖かい", jpExtra: "あたたかい", en: "Warm"),
    Word(jp: "気圧", jpExtra: "きあつ", en: "Atmospheric Pressure"),
    Word(jp: "高気圧", jpExtra: "こうきあつ", en: "High Pressure"),
    Word(jp: "低気圧", jpExtra: "ていきあつ", en: "Low Pressure"),
    Word(jp: "天気予報", jpExtra: "てんきよほう", en: "Weather Forecast"),
    Word(jp: "快晴", jpExtra: "かいせい", en: "Clear Sky"),
    Word(jp: "小雨", jpExtra: "こさめ", en: "Light Rain"),
    Word(jp: "大雨", jpExtra: "おおあめ", en: "Heavy Rain"),
    Word(jp: "豪雨", jpExtra: "ごうう", en: "Downpour"),
    Word(jp: "梅雨", jpExtra: "つゆ", en: "Rainy Season"),
    Word(jp: "虹", jpExtra: "にじ", en: "Rainbow"),
    Word(jp: "雪だるま", jpExtra: "ゆきだるま", en: "Snowman"),
    Word(jp: "雪かき", jpExtra: "ゆきかき", en: "Snow Shoveling"),
    Word(jp: "日差し", jpExtra: "ひざし", en: "Sunlight"),
    Word(jp: "夕立", jpExtra: "ゆうだち", en: "Evening Shower"),
    Word(jp: "雷雨", jpExtra: "らいう", en: "Thunderstorm"),
    Word(jp: "霧雨", jpExtra: "きりさめ", en: "Drizzle"),
    Word(jp: "降水量", jpExtra: "こうすいりょう", en: "Precipitation"),
    Word(jp: "氷点下", jpExtra: "ひょうてんか", en: "Below Freezing"),
    Word(jp: "猛暑", jpExtra: "もうしょ", en: "Heat Wave"),
    Word(jp: "冷夏", jpExtra: "れいか", en: "Cool Summer"),
    Word(jp: "暖冬", jpExtra: "だんとう", en: "Mild Winter"),
    Word(jp: "寒波", jpExtra: "かんぱ", en: "Cold Wave"),
    Word(jp: "雷鳴", jpExtra: "らいめい", en: "Thunderclap"),
    Word(jp: "夜露", jpExtra: "よつゆ", en: "Dew"),
    Word(jp: "曇天", jpExtra: "どんてん", en: "Overcast"),
    Word(jp: "春風", jpExtra: "はるかぜ", en: "Spring Breeze"),
    Word(jp: "秋晴れ", jpExtra: "あきばれ", en: "Autumn Clear Sky"),
    Word(jp: "冬嵐", jpExtra: "ふゆあらし", en: "Winter Storm"),
    Word(jp: "夏日", jpExtra: "なつび", en: "Summer Day"),
    Word(jp: "乾季", jpExtra: "かんき", en: "Dry Season"),
    Word(jp: "雨季", jpExtra: "うき", en: "Rainy Season"),
    Word(jp: "夕焼け", jpExtra: "ゆうやけ", en: "Sunset Glow"),
    Word(jp: "朝霧", jpExtra: "あさぎり", en: "Morning Mist")
]
